export const dogPackages = [
    {
      title: "Spa Bath",
      price: "₹999",
      originalPrice: "₹1198",
      features: [
        "Bath With Shampoo & Conditioner",
        "Blow Dry",
        "Nail Clipping",
        "Ear Cleaning",
        "Eyes Cleaning",
        "Paw Massage",
        "Combing/Brushing",
      ],
    },
    {
      title: "Bath + Basic Grooming",
      price: "₹1499",
      originalPrice: "₹1798",
      features: [
        "Bath With Shampoo & Conditioner",
        "Blow Dry",
        "Face Haircutting",
        "Sanitary Trim",
        "Nail Clipping",
        "Ear Cleaning",
        "Eye Cleaning",
        "Teeth Cleaning/Mouth Spray",
        "Paw Massage",
        "Combing/Brushing",
      ],
    },
    {
      title: "Full Service",
      price: "₹1999",
      originalPrice: "₹2398",
      features: [
        "Bath With Shampoo & Conditioner",
        "Blow Dry",
        "Full Body Trimming/Zero Haircut",
        "Eye Cleaning",
        "Ear Cleaning",
        "Body Massage",
        "Sanitary Trim",
        "Nail Clipping",
        "Teeth Cleaning/Mouth Spray",
        "Paw Massage",
        "Combing/Brushing",
      ],
    },
    {
      title: "PawLuxe",
      price: "₹2499",
      originalPrice: "₹2998",
      features: [
        "Bath With Shampoo & Conditioner",
        "Blow Dry",
        "Hair Styling",
        "De-Matting",
        "Tick Removal By Hand",
        "Anti-Tick Treatment",
        "Eye Cleaning",
        "Ear Cleaning",
        "Body Massage",
        "Sanitary Clipping",
        "Nail Clipping",
        "Teeth Cleaning/Mouth Spray",
        "Paw Massage",
        "Combing/Brushing",
      ],
    },
    {
      title: "Trans-fur-mation",
      price: "₹1499",
      originalPrice: "₹1798",
      features: [
        "Full Body Trimming",
        "Ear Cleaning",
        "Eyes Cleaning",
        "Nail Clipping",
      ],
    },
  ];
  
  export const catPackages = [
    {
      title: "Spa Bath",
      price: "₹999",
      originalPrice: "₹1198",
      features: [
        "Bath With Shampoo & Conditioner",
        "Blow Dry",
        "Nail Clipping",
        "Ear Cleaning",
        "Eyes Cleaning",
        "Paw Massage",
        "Combing/Brushing",
      ],
    },
    {
      title: "Bath + Basic Grooming",
      price: "₹1499",
      originalPrice: "₹1798",
      features: [
        "Bath With Shampoo & Conditioner",
        "Blow Dry",
        "Face Haircutting",
        "Sanitary Trim",
        "Nail Clipping",
        "Ear Cleaning",
        "Eye Cleaning",
        "Teeth Cleaning/Mouth Spray",
        "Paw Massage",
        "Combing/Brushing",
      ],
    },
    {
      title: "Full Service",
      price: "₹1999",
      originalPrice: "₹2398",
      features: [
        "Bath With Shampoo & Conditioner",
        "Blow Dry",
        "Full Body Trimming/Zero Haircut",
        "Eye Cleaning",
        "Ear Cleaning",
        "Body Massage",
        "Sanitary Trim",
        "Nail Clipping",
        "Teeth Cleaning/Mouth Spray",
        "Paw Massage",
        "Combing/Brushing",
      ],
    }
  ];
  