// dummyPets.ts
import { Pet } from '../types'; // Adjust the import path based on your project structure

// Indian states and cities
const indianLocations = [
  { state: "Maharashtra", city: "Mumbai" },
  { state: "Maharashtra", city: "Pune" },
  { state: "Delhi", city: "New Delhi" },
  { state: "Karnataka", city: "Bangalore" },
  { state: "Karnataka", city: "Mysore" },
  { state: "Tamil Nadu", city: "Chennai" },
  { state: "Tamil Nadu", city: "Coimbatore" },
  { state: "West Bengal", city: "Kolkata" },
  { state: "Uttar Pradesh", city: "Lucknow" },
  { state: "Uttar Pradesh", city: "Agra" },
  { state: "Rajasthan", city: "Jaipur" },
  { state: "Rajasthan", city: "Udaipur" },
  { state: "Gujarat", city: "Ahmedabad" },
  { state: "Gujarat", city: "Surat" },
  { state: "Kerala", city: "Kochi" },
  { state: "Kerala", city: "Thiruvananthapuram" },
  { state: "Punjab", city: "Amritsar" },
  { state: "Punjab", city: "Ludhiana" },
  { state: "Telangana", city: "Hyderabad" },
  { state: "Andhra Pradesh", city: "Visakhapatnam" },
];

// 10 Dogs with realistic names and breed-specific images
const dogs: Pet[] = [
  {
    id: 1,
    name: "Rocky",
    age: 3,
    ageUnit: "years",
    petType: "Dog",
    petBreed: "Indian Pariah",
    state: indianLocations[0].state,
    city: indianLocations[0].city,
    contact: "rahul.sharma@example.com",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Indian_Pariah_Dog.jpg/320px-Indian_Pariah_Dog.jpg",
    userId: "user-rahul",
  },
  {
    id: 2,
    name: "Max",
    age: 2,
    ageUnit: "years",
    petType: "Dog",
    petBreed: "Labrador Retriever",
    state: indianLocations[1].state,
    city: indianLocations[1].city,
    contact: "priya.verma@example.com",
    image: "https://images.unsplash.com/photo-1596492786367-3e8f2d4b24e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-priya",
  },
  {
    id: 3,
    name: "Bruno",
    age: 4,
    ageUnit: "years",
    petType: "Dog",
    petBreed: "German Shepherd",
    state: indianLocations[2].state,
    city: indianLocations[2].city,
    contact: "arjun.mehta@example.com",
    image: "https://images.unsplash.com/photo-1601758176175-459143795273?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-arjun",
  },
  {
    id: 4,
    name: "Tommy",
    age: 1,
    ageUnit: "years",
    petType: "Dog",
    petBreed: "Golden Retriever",
    state: indianLocations[3].state,
    city: indianLocations[3].city,
    contact: "neha.singh@example.com",
    image: "https://images.unsplash.com/photo-1631031138706-294d3b165879?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-neha",
  },
  {
    id: 5,
    name: "Sheru",
    age: 5,
    ageUnit: "years",
    petType: "Dog",
    petBreed: "Beagle",
    state: indianLocations[4].state,
    city: indianLocations[4].city,
    contact: "vikas.patel@example.com",
    image: "https://images.unsplash.com/photo-1517849845537-4d257902454a?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-vikas",
  },
  {
    id: 6,
    name: "Leo",
    age: 2,
    ageUnit: "years",
    petType: "Dog",
    petBreed: "Pug",
    state: indianLocations[5].state,
    city: indianLocations[5].city,
    contact: "anita.desai@example.com",
    image: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-anita",
  },
  {
    id: 7,
    name: "Raja",
    age: 3,
    ageUnit: "years",
    petType: "Dog",
    petBreed: "Rottweiler",
    state: indianLocations[6].state,
    city: indianLocations[6].city,
    contact: "suresh.kumar@example.com",
    image: "https://images.unsplash.com/photo-1601758064206-8c2a754cf5fe?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-suresh",
  },
  {
    id: 8,
    name: "Milo",
    age: 4,
    ageUnit: "years",
    petType: "Dog",
    petBreed: "Siberian Husky",
    state: indianLocations[7].state,
    city: indianLocations[7].city,
    contact: "deepika.roy@example.com",
    image: "https://images.unsplash.com/photo-1601758260734-43c6e26e8a8e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-deepika",
  },
  {
    id: 9,
    name: "Charlie",
    age: 1,
    ageUnit: "years",
    petType: "Dog",
    petBreed: "Dachshund",
    state: indianLocations[8].state,
    city: indianLocations[8].city,
    contact: "rohit.gupta@example.com",
    image: "https://images.unsplash.com/photo-1583519475385-558a3748c819?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-rohit",
  },
  {
    id: 10,
    name: "Tyson",
    age: 2,
    ageUnit: "years",
    petType: "Dog",
    petBreed: "Boxer",
    state: indianLocations[9].state,
    city: indianLocations[9].city,
    contact: "kavita.nair@example.com",
    image: "https://images.unsplash.com/photo-1601758066447-281e4c437e85?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-kavita",
  },
];

// 10 Cats with realistic names and breed-specific images
const cats: Pet[] = [
  {
    id: 11,
    name: "Mimi",
    age: 2,
    ageUnit: "years",
    petType: "Cat",
    petBreed: "Indian Domestic",
    state: indianLocations[10].state,
    city: indianLocations[10].city,
    contact: "pooja.jain@example.com",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Indian_street_cat.jpg/320px-Indian_street_cat.jpg",
    userId: "user-pooja",
  },
  {
    id: 12,
    name: "Luna",
    age: 3,
    ageUnit: "years",
    petType: "Cat",
    petBreed: "Persian",
    state: indianLocations[11].state,
    city: indianLocations[11].city,
    contact: "amit.bose@example.com",
    image: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-amit",
  },
  {
    id: 13,
    name: "Tara",
    age: 1,
    ageUnit: "years",
    petType: "Cat",
    petBreed: "Siamese",
    state: indianLocations[12].state,
    city: indianLocations[12].city,
    contact: "sneha.reddy@example.com",
    image: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-sneha",
  },
  {
    id: 14,
    name: "Snowy",
    age: 4,
    ageUnit: "years",
    petType: "Cat",
    petBreed: "Maine Coon",
    state: indianLocations[13].state,
    city: indianLocations[13].city,
    contact: "manoj.thakur@example.com",
    image: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-manoj",
  },
  {
    id: 15,
    name: "Chiku",
    age: 2,
    ageUnit: "years",
    petType: "Cat",
    petBreed: "Bengal",
    state: indianLocations[14].state,
    city: indianLocations[14].city,
    contact: "rani.mishra@example.com",
    image: "https://images.unsplash.com/photo-1606214174585-fe315fa3a017?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-rani",
  },
  {
    id: 16,
    name: "Pinky",
    age: 3,
    ageUnit: "years",
    petType: "Cat",
    petBreed: "Ragdoll",
    state: indianLocations[15].state,
    city: indianLocations[15].city,
    contact: "anil.yadav@example.com",
    image: "https://images.unsplash.com/photo-1615807713086-bfc49740e902?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-anil",
  },
  {
    id: 17,
    name: "Shadow",
    age: 5,
    ageUnit: "years",
    petType: "Cat",
    petBreed: "Sphynx",
    state: indianLocations[16].state,
    city: indianLocations[16].city,
    contact: "divya.chopra@example.com",
    image: "https://images.unsplash.com/photo-1529258289375-8bf6a6695a85?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-divya",
  },
  {
    id: 18,
    name: "Misty",
    age: 2,
    ageUnit: "years",
    petType: "Cat",
    petBreed: "British Shorthair",
    state: indianLocations[17].state,
    city: indianLocations[17].city,
    contact: "sachin.kapoor@example.com",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-sachin",
  },
  {
    id: 19,
    name: "Roxy",
    age: 1,
    ageUnit: "years",
    petType: "Cat",
    petBreed: "Abyssinian",
    state: indianLocations[18].state,
    city: indianLocations[18].city,
    contact: "meera.das@example.com",
    image: "https://images.unsplash.com/photo-1606936756139-4b1d4866e514?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-meera",
  },
  {
    id: 20,
    name: "Coco",
    age: 3,
    ageUnit: "years",
    petType: "Cat",
    petBreed: "Scottish Fold",
    state: indianLocations[19].state,
    city: indianLocations[19].city,
    contact: "vivek.rao@example.com",
    image: "https://images.unsplash.com/photo-1533749047132-2ae36c46583d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    userId: "user-vivek",
  },
];

// Combine and shuffle pets
const dummyPets: Pet[] = [...dogs, ...cats].sort(() => Math.random() - 0.5);

export default dummyPets;